### PR TITLE
Operation generation mode from first tag and path segments

### PR DESCRIPTION
**Pull request by mikesingleton**
Adds new IOperationNameGenerator class (MultipleClientsFromFirstTagAndPathSegmentsOperationNameGenerator.cs) for generating {controller} using the first tag in each operation and generating the operation name based on the path

Related issues: #1823, #1805

### CODE REVIEW

**Comment by RSuter** [comment]
Thanks for the PR. Looks good to me!

**Comment by mikesingleton** [comment]
👍 Happy to help

**Comment by RSuter** [comment]
I've added two comments but when these are resolved we can merge...

**Comment by mikesingleton** [comment]
I don't see any comments or reviews on this PR. Any ideas?

**Comment by RSuter** [comment]
Sorry, now you should see them

**Comment by spfaeffli** [comment]
@mikesingleton Are you currently working on resolving these issues?

**Comment by mikesingleton** [comment]
@spfaeffli I got pulled onto something else, but I should be able to resolve this within a week or two. Hope the delay isn't too much of an inconvenience

**Comment by spfaeffli** [comment]
@mikesingleton Ok, thank you. If you need any help, let me know.

**Comment by nbowditch** [comment]
@spfaeffli - made those changes for my coworker, he's been pulled onto a different project. Let me know if there's anything else I can do

**Comment by RicoSuter** [comment]
Looks good to me, thank you very much. Ideally we would add unit tests and i’m wondering what happens if there is no tag? But it’s fine for me to merge now.

**Comment by nbowditch** [comment]
@RicoSuter - I'm about to push up a unit test for the new name generator, just fyi so you don't merge it

**Pull request merged**
