### PR TITLE
Prevent dispose of HttpClient in FileResponse

### PR DESCRIPTION
**Pull request by DominikPf**
This PR adresses #2981 

The if Statement is the same as in the Client Template (Check for InjectHttpClient == false and DisposeHttpClient == true)

https://github.com/RicoSuter/NSwag/blob/fb48ea9e48ef8ccacf9e7b8fa35af1f1dfa0c81b/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L336-L339

### CODE REVIEW

**Comment by RicoSuter** [comment]
> The if Statement is the same as in the Client Template

Where is this already present?

**Comment by DominikPf** [comment]
I meant the Dispose in the Client Template (Marked Lines in Client.liquid as mentioned in my comment above)

**Comment by jeremyVignelles** [comment]
Sorry, I didn't see your fix at first when creating #3016. The way things were written made me think that the proper fix is to pass `null` the FileResult constructor, instead of testing in the FileResult template.

**Comment by DominikPf** [comment]
@jeremyVignelles No Problem, i'm ok with that. I am closing this PR in favor of #3016

**Pull request closed without merging**
