### PR TITLE
Add NET 9 support, drop NET 6 support

### LINKED ISSUE #5022: .Net 9 Support
Hi,

Any chance of getting a NSwagExe_Net90 version soon? (even without any other changes).
Currently we have to install .net 8 in the docker images in order to produce the client which adds a lot of build time.
I couldn't find an issue for this or something mentioning .net 9 so I opened this one. Please feel free to close and link to an existing issue if there is one.

Thanks!

### PR DESCRIPTION
**Pull request by lahma**
NET 6 is EOL and NET 9 is the latest release.

fixes #5022

### CODE REVIEW

**Comment by RicoSuter** [comment]
@lahma is this ready to be merged?

**Comment by lahma** [comment]
Should be, I followed earlier PRs and what was needed. Maybe preview quality still needing field testing though.

**Comment by RicoSuter** [comment]
@lahma can you maybe update with latest develop (conflicts)?

**Comment by RicoSuter** [comment]
> > @lahma can you maybe update with latest develop (conflicts)?
> 
> I guess you beat me to it 😄

Sorry, I have the day off today and I want to get this rolling today :-)

**Pull request merged**
