### PR TITLE
NSwag.AspNetCore: Fixed dependencies for Net6.0.

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/RicoSuter/NSwag/issues/3699 (Hopefully, I couldn't check it properly as NetFramework 4.5 and 4.5.1 is no longer installed on my machine --> End of life).

### CODE REVIEW

**Comment by Hylaean** [comment]
It looks like the azure yml pipeline needs to be updated for this PR

  # Install required SDKs and tools
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '5.0.100'

6.0.100 there and you should be good to go

**Comment by Hylaean** [comment]
Hello again,

<MicrosoftExtensionsFileProvidersEmbeddedPackageVersionNet6>[6.0</MicrosoftExtensionsFileProvidersEmbeddedPackageVersionNet6>

It seems this is an incorrect version spec. [6, 7.0) would maintain the previous tradition.

**Comment by SeppPenner** [comment]
> 
> 
> Hello again,
> 
> ```
> <MicrosoftExtensionsFileProvidersEmbeddedPackageVersionNet6>[6.0</MicrosoftExtensionsFileProvidersEmbeddedPackageVersionNet6>
> ```
> 
> It seems this is an incorrect version spec. [6, 7.0) would maintain the previous tradition.

Yeah, seems legit.

**Comment by RicoSuter** [comment]
I think this PR is not needed because it's already covered by this PR: 
https://github.com/RicoSuter/NSwag/pull/3632

**Comment by SeppPenner** [comment]
> 
> 
> I think this PR is not needed because it's already covered by this PR: #3632

True, I missed this one...

**Comment by RicoSuter** [comment]
NSwag with .NET 6 support is released: Try v13.14.0

**Pull request closed without merging**
