### PR TITLE
Fixes an issue where nullable ENUM query parameter had double OneOf -schema

### PR DESCRIPTION
**Pull request by Havunen**
Fixes an issue where nullable ENUM query parameter had double OneOf -schema
Fixes an issue where nullable collection of Enums query parameter was defined as request body in GET method

### CODE REVIEW

**Comment by Havunen** [comment]
@RicoSuter Can you review this change please :)

**Comment by Havunen** [comment]
@RicoSuter Can you please review this its roadblocker for our OpenAPI 3 project

**Comment by RicoSuter** [comment]
Can you post a part of a spec how it's currently generated vs how it's done in the changes?

**Comment by Havunen** [comment]
>Can you post a part of a spec how it's currently generated vs how it's done in the changes?

I was trying to give example from the test case I added, and I noticed it produces identical code before and after the fix. So the test case is not doing what is was supposed to do. I will look into it. 

Anyway; currently the NSwag generator OpenAPI 3 schema like this for some enum parameters:

```
        "parameters": [
          {
            "name": "integrationName",
            "in": "query",
            "description": "Optional: The integration of which logs you want.",
            "schema": {
              "oneOf": [
                {
                  "nullable": true,
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/Integration"
                    }
                  ]
                }
              ]
            },
            "x-position": 1
          },
```
It should have only one of those "oneOf" and have nullable property at schema. I will look into the test case and change it accordingly

**Comment by RicoSuter** [comment]
I think the changes in CreatePrimitiveOpenApiParameter will remove the inner oneOf and not the outer one...
I think the fix needs to be done somewhere else (ie avoid the outer oneOf ref completely).

**Comment by Havunen** [comment]
I will debug this tomorrow and create proper test case first to reproduce the issue.

**Comment by Havunen** [comment]
I created new PR for test case here: https://github.com/RicoSuter/NSwag/pull/3124

**Pull request closed without merging**
