### PR TITLE
Add repository metadata to NuGet packages

### PR DESCRIPTION
**Pull request by pascalberger**
Add repository metadata to NuGet packages

### CODE REVIEW

**Comment by RicoSuter** [comment]
The correct URL is actually https://github.com/RicoSuter/NSwag.git

What benefits do we have with this additional information?

**Comment by pascalberger** [comment]
> The correct URL is actually https://github.com/RicoSuter/NSwag.git

I'll update this

> What benefits do we have with this additional information?

This will show a link to the repository on nuget.org. See [here](https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/) for details.
This is the same as the project link as long as nswag.org redirects to GitHub, but makes it more explicit.

**Comment by pascalberger** [comment]
> The correct URL is actually https://github.com/RicoSuter/NSwag.git

I've updated the URLs

**Comment by RicoSuter** [comment]
Thanks for the PR!

**Pull request merged**
