### PR TITLE
Add Controller extension template

### PR DESCRIPTION
**Pull request by gillesdb**
This PR contains a generic extension template for OpenAPI to CSharp controllers that can be used for different purposes.

_Example_
I would like to use this template to setup authZ by making use of policies:
```
// Controller.Method.Annotations.liquid
[Microsoft.Owin.Security.Authorization.WebApi.ResourceAuthorize(Policy = Policies.{{ operation.ActualOperationName }})]

// Controller.Extensions.liquid
public class Policies
{
{% for operation in Operations -%}
    public const string {{ operation.ActualOperationName }} = nameof({{ operation.ActualOperationName }});
{% endfor -%}
}

// Startup.cs
app.UseAuthorization(options =>
{
    options.AddPolicy(Policies.MyOperationName, policyBuilder => policyBuilder.RequireClaim(ClaimTypes.Role, Claims.ReadApplications, Claims.ManageApplications));
});
```
Thanks for considering this pull-request!

### CODE REVIEW

**Comment by RicoSuter** [comment]
I think this is not needed. Just overwrite Controller.liquid with

```
{% template %}

Your stuff
```

This will use the original tpl and apprnd your code.

**Comment by gillesdb** [comment]
@RicoSuter Using this approach I was not able to add extensions. The controller part wasn't generated anymore:
image

**Comment by RicoSuter** [comment]
What about overriding the File.template in the same way?

**Comment by gillesdb** [comment]
@RicoSuter No, unfortunately, this does not work either. (see image below).
In the meantime, I also found your wiki about templates from NjsonSchema:
 https://github.com/RicoSuter/NJsonSchema/wiki/Templates 

So I decided to also test this 'override template' feature for classes, but also without success.

image

**Comment by RicoSuter** [comment]
Looks like a bug in the templating system

**Comment by RicoSuter** [comment]
So this is can be merged (is fixed) when the referenced PR is in?

**Comment by RicoSuter** [comment]
Or is this not needed anymore?

**Comment by gillesdb** [comment]
This PR can be closed, thanks for your assistance!
Example:

```
// Controller.Method.Annotations.liquid
[Microsoft.Owin.Security.Authorization.WebApi.ResourceAuthorize(Policy = Policies.{{ operation.ActualOperationName }})]

// controller.liquid
{% template %}
public class Policies
{
{% for operation in Operations -%}
    public const string {{ operation.ActualOperationName }} = nameof({{ operation.ActualOperationName }});
{% endfor -%}
}
```
Policies Example

Linked PR: https://github.com/RicoSuter/NSwag/pull/2735

**Comment by RicoSuter** [comment]
Will release v13.3.0 in the next minutes...

**Comment by RicoSuter** [comment]
... just running the latest integration tests etc.

**Pull request closed without merging**
