### PR TITLE
LeafType test improvements

### PR DESCRIPTION
**Pull request by trejjam**
This PR improves tests for fixed leafType code (related to https://github.com/RicoSuter/NJsonSchema/pull/1382)

### CODE REVIEW

**Comment by RicoSuter** [comment]
Did i miss some pkgs?
https://github.com/RicoSuter/NSwag/commit/a4c86758b14ff4eaf77aede352263f0facb08ce3

**Comment by trejjam** [comment]
Oh, I miss it, I will check it in the morning

**Comment by trejjam** [comment]
Rebased

**Comment by RicoSuter** [comment]
Thanks for the PR.

**Pull request merged**
