### PR TITLE
[TS] Add AbortSignal to fetch template

### PR DESCRIPTION
**Pull request by nulladdict**
This adds support for [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) for Fetch template
I've mostly followed [this PR](https://github.com/RicoSuter/NSwag/pull/2846/) for axios

One thing I'm concerned about is that it seems like `AbortSignal` typings were [added](https://github.com/microsoft/TypeScript/issues/19418) in TypeScript 2.7, so I wonder if signal generation should be opt-in through some kind of setting

### CODE REVIEW

**Comment by nulladdict** [comment]
I've added conditional generation, depending on TypeScript version.
I wasn't sure if this should've been a separate setting, or computed from TypeScript version,
but I guess this should be fine, since generated `signal` is optional parameter

**Comment by RicoSuter** [comment]
> I wasn't sure if this should've been a separate setting, or computed from TypeScript version,

Is this a feature which is supported in all browsers/fetch implementations?
Why is this dependent on the TS version?
If it's not supported in older versions/not in all fetch versions than we should probably put this behind a config..

**Comment by RicoSuter** [comment]
It's even experimental: 

image

**Comment by nulladdict** [comment]
The original discussion about aborting fetch ([1](https://github.com/whatwg/fetch/issues/27)) ([2](https://github.com/whatwg/fetch/issues/447)) ended up using `AbortSignal` for [`Request`](https://fetch.spec.whatwg.org/#request-class), but I guess `AbortSignal` & `AbortController` are still considered experimental
Generally speaking, modern browsers that support `fetch` tend to also support this api, but additional polyfills might be [necessary](https://github.com/github/fetch#aborting-requests)

I don't mind hiding this behind a config setting

Also, it's dependent on the TS version, because earlier versions didn't have types for `AbortSignal` & `AbortController`, but I think if we're putting this behind a setting this might not be relevant

**Comment by RicoSuter** [comment]
As its experimental and potentially a breaking change i think its better to put this behind a config (UseAbortSignal, default: false). Is that ok? Can you update the PR?

**Comment by nulladdict** [comment]
Sounds good to me, I'll update the PR

**Comment by RicoSuter** [comment]
@nulladdict can we merge this PR?

**Comment by nulladdict** [comment]
I think so, if there are no problems with liquid template.
I am not very experienced with it, it looks fine for me, but I might be missing something

**Comment by RicoSuter** [comment]
Lgtm, thanks for the PR.

**Comment by nulladdict** [comment]
No problem, should we also update the documentation for new `UseAbortSignal` config?
I'm not sure what (if anything) needs to be done to update [the wiki](https://github.com/RicoSuter/NSwag/wiki/TypeScriptClientGeneratorSettings)

**Comment by RicoSuter** [comment]
image

**Comment by RicoSuter** [comment]
Just add a new group there and document it -that's probably fine

**Pull request merged**
