### PR TITLE
Cleanup JsonSerializerParameterCode

### PR DESCRIPTION
**Pull request by unchase**
* Add `CSharpClientTemplateModel.JsonConvertersArrayCode`
* Fix `Client.Class.liquid`

Instead of #3350

### CODE REVIEW

**Comment by unchase** [comment]
Related: https://github.com/RicoSuter/NJsonSchema/pull/1341

**Comment by RicoSuter** [comment]
Is this also ready? 
I'd like to update NJS and then also release NSwag with the updates.

**Comment by unchase** [comment]
> Is this also ready?
> I'd like to update NJS and then also release NSwag with the updates.

Yes.
Just need to run tests after updating NJS to make sure everything is good.

**Comment by RicoSuter** [comment]
Updated your branch with the latest NJS version... 
Can you finish the PR?

**Comment by unchase** [comment]
> Updated your branch with the latest NJS version...
> Can you update the PR or is it ready?

@RicoSuter 
Added more tests. Now it is ready.

**Pull request merged**
