### PR TITLE
Net6 support

### PR DESCRIPTION
**Pull request by SeanMollet**
Exactly what the title says.. this is support for .net 6-RC1. Everything appears to work correctly.

I freely contribute my work under the same MIT license as the project. Thanks for making such a handy tool!

### CODE REVIEW

**Comment by Wezea** [comment]
I am looking very forward to that one 👍

**Comment by MichaelKueh** [comment]
Are there any plans when this PR will be checked/accepted?

**Comment by RicoSuter** [comment]
This now requires the .NET 6 sdk installed in the Nuke build. @lahma how can we add this dependency to the nuke build? I cannot find the place where currently the .NET 5 sdk is installed...

**Comment by lahma** [comment]
@RicoSuter should that `global.json` be at repo root, NUKE at cannot see it now as nuke is under `build`, not `src``?

**Comment by RicoSuter** [comment]
@lahma makes sense, however with the current setup i think we need multple sdks (e.g. .NET 5 and .NET 6 sdks...)

https://github.com/RicoSuter/NSwag/runs/4166404439?check_suite_focus=true

**Comment by asadsahi** [comment]
Thanks @RicoSuter Any idea when you are planning on releasing this .net 6 supported version? Really looking forward for this fix.

**Comment by RicoSuter** [comment]
@asadsahi I'd like to release it soon, however the build pipelines are broken at the moment...

**Comment by lahma** [comment]
> @lahma makes sense, however with the current setup i think we need multple sdks (e.g. .NET 5 and .NET 6 sdks...)
 
@RicoSuter working on it https://github.com/RicoSuter/NSwag/pull/3703

**Comment by alsami** [comment]
> @asadsahi I'd like to release it soon, however the build pipelines are broken at the moment...

Are you planning to release any time soon?

**Comment by thestamp** [comment]
Trying the new v13.14.0 build and I am getting errors when targeting .NET 6 when using `NSwagExe_Net60`:

```
1>System.InvalidOperationException: The Startup class could not be determined in the assembly 'Template.User.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\OpenApiGeneratorCommandBase.cs:line 345
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 323
1>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 76
1>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at System.Threading.Tasks.Task`1.InnerInvoke()
1>   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>--- End of stack trace from previous location ---
1>   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
1>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
1>--- End of stack trace from previous location ---
1>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 61
1>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 51
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 98
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 55
```

Startup.cs and Program.cs has been combined into Program.cs in the aspnet 6 webapi code template, so that might be the cause.

**Comment by RicoSuter** [comment]
Released, CLI broken, patch soon: 
https://github.com/RicoSuter/NSwag/pull/3713

**Pull request merged**
