### PR TITLE
Migrate to PackageReference from packages.config

### PR DESCRIPTION
**Pull request by lahma**
The `packages.config` is a pain and hard to maintain. This PR switches to using `PackageReference` elements in the solution which also works for older csprojs.

### CODE REVIEW

**Comment by lahma** [comment]
@RicoSuter ping 🙂

**Comment by RicoSuter** [comment]
This is great. I tried this in the past but back then eg WPF was not supported...
Thanks for the PR!

**Comment by RicoSuter** [comment]
Btw, we now have > 400 errors in the master CI build: 
https://ci.appveyor.com/project/rsuter/nswag-25x6o/builds/38865113
did you run the build scripts locally?

**Comment by lahma** [comment]
@RicoSuter sorry for those warnings, it's usually hard to see the forest from the trees as there are quite many due to XML comments. I see that you already pushed fixes, can I still help with something?

**Comment by lahma** [comment]
I will do a PR to clean up those warnings to make some amends.

**Comment by RicoSuter** [comment]
It was about the errors but it should be fixed now...
Now appvayor and devops ci run in parallel and soon ill remove appvayor in favor of devops... need to setup the release procedures first

**Comment by lahma** [comment]
I created https://github.com/RicoSuter/NSwag/pull/3437 to reduce noise and improve build configuration.

**Comment by lahma** [comment]
> Now appvayor and devops ci run in parallel and soon ill remove appvayor in favor of devops... need to setup the release procedures first

Out of curiosity, why not GitHub actions? I've somehow got the feeling that they are sunsetting devops now that GHA has all the feature push, better integrated too. I know that you have time invested in ADO at least.

**Pull request merged**
