### PR TITLE
Multiple version installation for `actions/checkout@v3`

### PR DESCRIPTION
**Pull request by Saibamen**
Addendum to https://github.com/RicoSuter/NSwag/pull/4220

### CODE REVIEW

**Comment by lahma** [comment]
These files are automatically generated. Why do you want these changes applied?

**Comment by Saibamen** [comment]
One action should be a little bit faster than 5

**Comment by lahma** [comment]
If you run build.cmd you'll probably see the file being overwritten, so this approach won't work.

**Comment by Saibamen** [comment]
73 vs 133 seconds
image

**Comment by Saibamen** [comment]
You should also update `actions/checkout` to `v3` and `actions/cache` to `v3`

**Comment by lahma** [comment]
This has been resolved in master

**Pull request closed without merging**
