### PR TITLE
sdk methods generated as virtual methods

### PR DESCRIPTION
**Pull request by rw-ben**
@RicoSuter  This updates the Client.Class.liquid template to make SDK methods generated as virtual methods.

How it could be used from class that inherits generated sdk class:
```
        public override Task<SwaggerResponse<CompanyFeature>> GetCompanyFeatureByCompanyIdAsync(int companyId, CancellationToken cancellationToken = default)
        {
          //some code needed to extend goes here (ex. maybe some small cache code)
        }
```

Original output:
```
        public async System.Threading.Tasks.Task<SwaggerResponse<CompanyFeature>> GetCompanyFeatureByCompanyIdAsync(int companyId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
```

New output:
```
        public virtual async System.Threading.Tasks.Task<SwaggerResponse<CompanyFeature>> GetCompanyFeatureByCompanyIdAsync(int companyId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
```

### CODE REVIEW

**Comment by rw-ben** [comment]
@jonlin noticed issue 2704 you previously posted

**Comment by rw-ben** [comment]
@RicoSuter added VirtualMethods parameter options in C# generator and made it optional + default to false

**Comment by rw-ben** [comment]
@RicoSuter 

I noticed your comments on issue #2704 "Currently there is no option for that specifically.. you need to override the template and add the virtual modifier. The question is whether we should add this by default or if we should add an option. But maybe you can change the access modifier from “public” to “public virtual”?"

I was hoping to see if there were any concerns with this feature addition in this pull request. It defaults to existing functionality and has an option to enable the access modifier to be "public virtual" instead of "public".

Again appreciate your time.

**Comment by rw-ben** [comment]
@RicoSuter Would you kindly approve the workflow? I'm a first-time contributor.

**Comment by RicoSuter** [comment]
I wonder whether we really need to add a new setting for that (more complexity) or just add virtual to the template - performance wise these methods are "slow" anyway as they are I/O based and adding virtual is not a breaking change (right?). Opinions? /cc @lahma @jeremyVignelles

**Comment by lahma** [comment]
I don't see any harm for them being virtual by default. If the API would change it would anyway break the caller and also then the inheritor/override.

**Comment by jeremyVignelles** [comment]
OK for virtual by default. You know my opinion about adding an option for each use case :)

**Comment by RicoSuter** [comment]
@rw-ben ok I agree, let's remove the setting and just add virtual to the templates - then we have a quite simple PR.

**Comment by rw-ben** [comment]
@RicoSuter @jeremyVignelles @lahma thank you all for taking a look at this. I will make it default and push the changes up.

**Comment by rw-ben** [comment]
@RicoSuter @jeremyVignelles @lahma removed the virtual method C# generation param and it always generate virtual methods

**Comment by rw-ben** [comment]
@RicoSuter thanks

**Comment by RicoSuter** [comment]
Thanks for the PR.

**Comment by rw-ben** [comment]
@RicoSuter How do I get a new release built? Is this something you have to kick off?

**Comment by jkone27** [comment]
what about C# properties? they are not virtual is it possible to ovverride them too? (e.g. to give defaults to null/empty)

**Pull request merged**
