### PR TITLE
Add enumStyle option into the openApiToTypeScriptClient

### PR DESCRIPTION
**Pull request by trejjam**
- Update NJsonSchema to 10.1.7
- Add EnumStyle into the OpenApiToTypeScriptClientCommand.cs

### CODE REVIEW

**Comment by trejjam** [comment]
Sorry for the mess in the *.csproj files. Some of them were with BOM and some without it. Now changed are all without BOM.

**Comment by RicoSuter** [comment]
Ah shit, i just did that
https://github.com/RicoSuter/NSwag/commit/34d2924b06610f2d362db66513fe96c5e85420ec

**Comment by trejjam** [comment]
I will move it on top of develop

**Comment by RicoSuter** [comment]
Update command and UI: https://github.com/RicoSuter/NSwag/commit/110b107a3aa29bbab48957350ea2033bc5a9c099

**Comment by RicoSuter** [comment]
I think its fine now.

**Comment by trejjam** [comment]
Thanks! I like your work

**Comment by trejjam** [comment]
I think, this is now resolved https://github.com/RicoSuter/NSwag/issues/1188

**Comment by RicoSuter** [comment]
Yes, closed. So I will now release a new version of NSwag... ok?

**Comment by trejjam** [comment]
It will be lovely. I tested code generation, and it works like a charm.

**Comment by RicoSuter** [comment]
Ok, release is done. NuGet pkgs should be available now/soon.

**Pull request closed without merging**
