### PR TITLE
NSwag as a dotnet tool

### PR DESCRIPTION
**Pull request by Zache**
This pull requests adds another project to be published as a dotnet tool

To make this I simply followed [this tutorial to make the tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create) and [this tutorial to install and use it locally](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use), the NSwag.ConsoleCore project had almost everything right. I simply copied it and removed support for anything before .NET Core 2.1.

If you want to test this out, simply clone my branch locally and follow these steps taken from [the tutorial I linked earlier](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use):

1. Open your favorite terminal
2. `cd <src>/NSwag/src/NSwag.Tool`
3. `dotnet pack`
4. Now navigate to where you want to install the tool
5. `dotnet new tool-manifest`
6. `dotnet tool install --add-source <path to NSwag.Tool/bin, where the nupkg is>` NSwag.Tool
7. Try it out:
 ```
dotnet nswag openapi2cscontroller -- /input:"https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml" /namespace:Com.Example.Petstore /output:Controllers/PetstoreController.cs
```

This worked for me, on Windows and in a [docker container](https://gist.github.com/Zache/b7eb8a18d07ee531032fc6ad36fdbe3c). To publish the package to Nuget 

Related issues: #2244 #2024 #1931 #1358

### CODE REVIEW

**Comment by RicoSuter** [comment]
Can't we change the NSwag.ConsoleCore project to be a global tool instead?

**Comment by Zache** [comment]
If you want to remove target frameworks earlier than: netcoreapp2.1 which is the minimun requirement for a project to pack as a tool.

**Comment by RicoSuter** [comment]
I think NSwag.ConsoleCore is not really used (at least not in my projects) - so remove old frameworks (only .net core 1.x right?) is fine as they are deprecated anyway...

**Comment by Zache** [comment]
Done, I don't know how you version things but I took the liberty of bumping the version since removing supported frameworks feels like a breaking change to me. Once on NuGet you can install the tool: `dotnet tool install nswag.consolecore` and I use it like so: `dotnet nswag run nswag.json`

**Comment by RicoSuter** [comment]
Thanks for the PR.

**Comment by acds** [comment]
@RicoSuter Hi! When will the be available on the NuGet feed ?

**Comment by RicoSuter** [comment]
Its released now

**Comment by acds** [comment]
@RicoSuter I installed the Swag.ConsoleCore tool globally, with `dotnet tool install --global NSwag.ConsoleCore` but am getting this error:

```console
2>dotnet "/Users/xxxx/.nuget/packages/nswag.msbuild/13.4.2/build/../tools/NetCore31/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug,OutDir=bin/Debug/netcoreapp3.1/netcoreapp3.1/
2>NSwag command line tool for .NET Core NetCore31, toolchain v13.4.2.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v12.0.0.0))
2>Visit http://NSwag.org for more information.
2>NSwag bin directory: /Users/xxxx/.nuget/packages/nswag.msbuild/13.4.2/tools/NetCore31
2>
2>Executing file 'nswag.json' with variables 'Configuration=Debug,OutDir=bin/Debug/netcoreapp3.1/netcoreapp3.1/'...
2>System.InvalidOperationException: Process dotnet timed out.
2>   at NSwag.Commands.Generation.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\Exe.cs:line 70
2>   at NSwag.Commands.Generation.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, IConsoleHost console) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\ProjectMetadata.cs:line 143
2>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 103
2>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
2>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
2>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
```

I have this setup in my csproj
```xml
  <Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core31) run nswag.json /variables:Configuration=$(Configuration),OutDir=$(OutDir)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```
guess I'm missing something...

**Comment by RicoSuter** [comment]
The csproj thing works and cli doesnt? Maybe you need to set noBuild = true otherwise you’ll get into a infinite build loop

**Comment by acds** [comment]
@RicoSuter Thanks! Yes that helped...

I'm getting a wired `System.IO.IOException: Permission denied` exception from the `NetCore31` tool that seems to be related to an inability to write the files to generate the client to the output folder but it makes no sense. 

I have the nswag.json set the:
-  `documentGenerator:aspNetCoreToOpenApi:output` = `../HttpClient/openapi.json`
-  `codeGenerators:openApiToCSharpClient:output` = `../HttpClient`  

The `openapi.json` file is generated in the folder structure that is getting the exceptions as expected.

it would be great of each of the settings in the `nswag.json` file was also fully documented [here](https://github.com/RicoSuter/NSwag/wiki/NSwag-Configuration-Document. Since I'm developing on a non-Windows OS I have no easy way to run NSwagStudio

```log
2>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2> ---> System.UnauthorizedAccessException: Access to the path '{path to solution folder}/{solution folder}/HttpClient' is denied.
2> ---> System.IO.IOException: Permission denied
2>   --- End of inner exception stack trace ---
2>   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2>   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2>   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
2>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2>   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2>   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
2>   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
2>   --- End of inner exception stack trace ---
2>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
2>   at NJsonSchema.Infrastructure.DynamicApis.FileWriteAllText(String filePath, String text)
2>   at NSwag.Commands.OutputCommandExtensions.TryWriteFileOutputAsync(IOutputCommand command, String path, IConsoleHost host, Func`1 generator) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandExtensions.cs:line 45
2>   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 243
2>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 85
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
2>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
2>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
2>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
2>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
```

**Comment by acds** [comment]
@RicoSuter another point of note installing the CLI package via  `dotnet tool install --global NSwag.ConsoleCore` does not play nice if you have other `<targets\>` configured in your `csproj` file.

One has to remove the other  `<targets\>`, install an then put them back in again, this also causes a problem if you try and update the NSwag packages:

NSwag.AspNetCore
NSwag.MSBuild

**Comment by johnwc** [comment]
How do you call this using the `dotnet <command>` approach? As in `dotnet nswag openapi2csclient ...`

**Pull request merged**
