### PR TITLE
Replace bat files with NUKE build

### PR DESCRIPTION
**Pull request by lahma**
While getting Fluid to build I was once again faced with all sorts of build script problems, like location of MSBuild/Visual Studio etc (required VS developer command prompt to have PATH right). 

[NUKE](https://github.com/nuke-build/nuke) allows you to create build script using plain C# with great API and reduced risk of typos. Library also gives you full power of C# (loops, functions, encapsulation, variables and typing). It's really easy to adopt if you know C#. 

What I offer with this PR:

* new solution project `_build.csproj`
* all build logic neatly in `Build.cs`, should be quite readable
* transform `build\*.bat` files to call relevant NUKE targets, new targets in `Build.cs` contain the old bat file logic
* `build.cmd` and `build.sh` at repository root, easy to get started (Linux build possibility!)

**FUTURE**

* NUKE can generate appveyor, github actions, teamcity etc CI configurations if needed, no need to fight YAML
  * same targets can be invoked with appveyor, azure devops and github actions
* build on linux (needs some tweaks for targets / ignores), I've done this with multiple projects
* this will also benefit https://github.com/RicoSuter/NSwag/pull/3437 and https://github.com/RicoSuter/NSwag/pull/3679

Targets can be invoked using Windows command line with `build.cmd` (default compile), `build.cmd unittest` (UnitTests.bat functionality), configuration is automatically `Release` in CI environment (not a local build).

### CODE REVIEW

**Comment by RicoSuter** [comment]
Ok, ill have a look. Can i merge this PR and then continue with that?

**Comment by lahma** [comment]
Yes please, ping me if there's anything problematic you find.

**Comment by lahma** [comment]
The GitHub actions should light up after the merge, normal contributors cannot trigger workflow changes via PRs as it's a security risk.

**Comment by lahma** [comment]
@RicoSuter I've pushed couple PRs to fix two issues found by CI runs

**Pull request merged**
