### PR TITLE
Update .NET 8 RC references with RTM

### PR DESCRIPTION
**Pull request by lahma**

### CODE REVIEW

**Comment by ardalis** [comment]
Waiting on this so I can update some of my projects. Hope it's merged soon!

**Comment by thefakir** [comment]
> Waiting on this so I can update some of my projects. Hope it's merged soon!

+1

**Comment by thefakir** [comment]
now that is merged, when will be available in the nuget galery?

**Comment by RicoSuter** [comment]
v14.0.0-preview010
will hopefully release v14 next week

**Comment by ardalis** [comment]
Cool, thanks. Wish it were quicker but I understand.

My Clean Architecture template depends on FastEndpoints.
FastEndpoints depends on NSwag.
So I'm stuck at the end of the upgrade train...

Cheers...

**Comment by ilmax** [comment]
Hey @RicoSuter, any update on the net8.0 timeline? Is there something we can help you out with?

**Pull request merged**
