### PR TITLE
Improve IsXmlBodyParameter, IsBinaryBodyParameter and SwaggerRespons.IsBinary()

### LINKED ISSUE #2076: NSwagStudio v12.1.0.0 mis-generates `FileResponse` for regular response model
@RicoSuter - NSwagStudio v12.1.0.0 mis-generates `FileResponse` for regular response model definition which points to a C# custom class type.

I can send you swagger.json file to reproduce the bug - ping me at me@dmitry-pavlov.com

### PR DESCRIPTION
**Pull request by RicoSuter**
Closes #2076

### CODE REVIEW

**Comment by dmitry-pavlov** [comment]
Looks good to me @RicoSuter

**Comment by ljvanschie** [comment]
This could be tested by adding the following to https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Tests/SwaggerResponseTests.cs#L13, right?

```cs
[InlineData("*/*", false)]
[InlineData("application/json;charset=UTF-8", false)]
```

If I'm seeing it right, it didn't fix it yet.

**Comment by RicoSuter** [comment]
*/* doesnt make much sense to me TBH - how can you support everything?

**Comment by RicoSuter** [comment]
But ill add this special case

**Comment by RicoSuter** [comment]
Ok now?

**Comment by ljvanschie** [comment]
Thanks! I agree it's a bit odd, but some libraries (like Springfox) default to `*/*`, and I think in that case it's more safe to assume the result isn't binary.

Looks good now 👍 

The other case (`[InlineData("application/json;charset=UTF-8", false)]`) still fails, but I'm not sure if it's a valid `produces` value.

**Comment by RicoSuter** [comment]
Ok, I hope it's good enough now :-)

**Comment by ljvanschie** [comment]
Great, thanks! 🙌

**Comment by ljvanschie** [comment]
`produces` with value `*/*` is treated as binary again. I see the test has also been updated for this. Can this be reverted so that `*/*` is treated as a json response?

**Pull request merged**
