### PR TITLE
Cancellation token default value

### PR DESCRIPTION
**Pull request by goldsam**
This addresses both #2867 and #2642 by adding a default argument to CancellationTaken parameters in generated C# controllers.

### CODE REVIEW

**Comment by RicoSuter** [comment]
Thanks for the PR! Released soon.

**Comment by RicoSuter** [comment]
This broke quite some tests: 
image

**Comment by RicoSuter** [comment]
Fixed: https://github.com/RicoSuter/NSwag/commit/c3b6597f599a92d15538a362e56467ef4d1ecd71

**Comment by jacobpovar** [comment]
Shouldn't the default value for CancellationToken be `default(CancellationToken)` instead of `CancellationToken.None` ?.
I'm getting error `Default parameter value for 'cancellationToken' must be a compile-time constant` after update to 13.6.1.

**Comment by RicoSuter** [comment]
I wondered too but assumed the PR has been tested. Hopefully it’s fixed with the referenced PR.

**Pull request merged**
