### PR TITLE
Fix CapitalizeFirst method

### PR DESCRIPTION
**Pull request by adesam146**

### CODE REVIEW

**Comment by RicoSuter** [comment]
Why do we even need ToLowerInvariant?

**Comment by adesam146** [comment]
> Why do we even need ToLowerInvariant?

Yes true it's not needed? Updated

**Comment by adesam146** [comment]
Also any reason for the duplication of the method? (left it alone for now)

**Comment by RicoSuter** [comment]
> Also any reason for the duplication of the method? (left it alone for now)

Mainly because these are two independent implementations...

I think it's fine now... Thanks for the PR.

**Pull request merged**
