### PR TITLE
fix #3230 Improper x-www-forms-urlencoded values

### LINKED ISSUE #3230: C# client serializes request to JSON instead of application/x-www-form-urlencoded
I am using NSwag Studio v13.9.4.0.

When I generate the C# client for the OpenAPI specification found [here](https://developer.rapidsos.com/sites/default/files/2020-12/Auth2Token.yaml), I get an error when submitting a request to the server because the body contains JSON instead of URL-encoded form data.

Despite the JSON, the client _does_ set the content type of the request to `application/x-www-form-urlencoded`, so it's clearly parsing the content type correctly from the OpenAPI spec.

This may be the same or similar bug as reported in the following issues:

[Trouble with typescript generator for x-www-form-urlencoded endpoint #1338](https://github.com/RicoSuter/NSwag/issues/1338)
[[OpenApi 3.0.0] requestBody.content map gets ignored for x-www-form-urlencoded #1963](https://github.com/RicoSuter/NSwag/issues/1963)

I was able to solve this temporarily by modifying the [Client.Class.liquid](https://github.com/RicoSuter/NSwag/blob/3ac17d115283f5277e1261b9a0433cd2cd9de365/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid) template as follows:

```
{%     if operation.HasContent -%}
{%         if operation.HasBinaryBodyParameter -%}
{%             if operation.ContentParameter.HasBinaryBodyWithMultipleMimeTypes -%}
                var content_ = new System.Net.Http.StreamContent({{ operation.ContentParameter.VariableName }}.Data);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse({{ operation.ContentParameter.VariableName }}.ContentType);
{%             else -%}
                var content_ = new System.Net.Http.StreamContent({{ operation.ContentParameter.VariableName }});
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("{{ operation.Consumes }}");
{%             endif -%}
{%         elseif operation.HasXmlBodyParameter -%}
                var content_ = new System.Net.Http.StringContent({{ operation.ContentParameter.VariableName }});
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("{{ operation.Consumes }}");
{% comment %}This section was added to the default template to correctly serialize an object when the request requires content type application/x-www-form-urlencoded{% endcomment %}
{%         elseif operation.ConsumesFormUrlEncoded -%}
                var json_ = Newtonsoft.Json.JsonConvert.SerializeObject({{ operation.ContentParameter.VariableName }}, _settings.Value);
                var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);
                var content_ = new System.Net.Http.FormUrlEncodedContent(dictionary_);
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("{{ operation.Consumes }}");
{% comment %}End new section{% endcomment %}
{%         else -%}
                var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject({{ operation.ContentParameter.VariableName }}, {% if SerializeTypeInformation %}typeof({{ operation.ContentParameter.Type }}), {% endif %}{% if UseRequestAndResponseSerializationSettings %}_requestSettings{% else %}_settings{% endif %}.Value));
                content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("{{ operation.Consumes }}");
{%         endif -%}
                request_.Content = content_;
```

Will you incorporate this change (or a similar fix) in the next release?

### PR DESCRIPTION
**Pull request by nHellweg**
Apply fix from the suggestion in fix #3230 to the template so it does not need to be done in a client override

### CODE REVIEW

**Comment by RicoSuter** [comment]
@jeremiahmercier-3136 can you have a look at this PR?

**Comment by RicoSuter** [comment]
Thx for the PR.

**Comment by Michael21011** [comment]
@RicoSuter this commit does not fix issue with wrong ContentType=application/json instead of correct x-www-form-urlencoded when FormUrlEncodedContent is used.
Currently next code is generated in NSqagStudio v13.15.5.0
`var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(dealershipIds, _settings.Value);
                    var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);
                    var content_ = new System.Net.Http.FormUrlEncodedContent(dictionary_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("x-www-form-urlencoded");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));`

**Comment by FleurLotus** [comment]
This change has side effect, 

when generating a default api with Visual Studio, the defaults formatters are
- JsonMediaTypeFormatter
- XMLMediaTypeFormatter
- FormUrlEncodedMediaTypeFormatter
- JQueryMvcFormUrlEncodedFormatter

with a simple controller like :

> [RoutePrefix("api")]
 public` class MyController : ApiController
{
    [HttpPost]
    [Route("Test")]
    public OutputData Test([FromBody] InputData test)
    {
        return new OutputData { Output = test?.Input };
    }
}
[Serializable]
public class InputData
{
    public string Input { get; set; }
}
[Serializable]
public class OutputData
{
    public string Output { get; set; }
}

the generated json for the swagger contains the  "application/x-www-form-urlencoded" in the consumers

>{"swagger":"2.0","info":{"version":"v1","title":"Test Service"},"host":"localhost:9002","schemes":["http"],"paths":{"/api/Test":{"post":{"tags":["My"],"operationId":"My_Test","consumes":["application/json","text/json","application/xml","text/xml","application/x-www-form-urlencoded"],"produces":["application/json","text/json","application/xml","text/xml"],"parameters":[{"name":"test","in":"body","required":true,"schema":{"$ref":"#/definitions/InputData"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/OutputData"}}}}}},"definitions":{"InputData":{"type":"object","properties":{"Input":{"type":"string"}}},"OutputData":{"type":"object","properties":{"Output":{"type":"string"}}}}}

the check on operation.ConsumesFormUrlEncoded make the C# code generated to look like:


>public virtual async System.Threading.Tasks.Task<OutputData> TestAsync(InputData test, System.Threading.CancellationToken cancellationToken)
        {
            if (test == null)
                throw new System.ArgumentNullException("test");
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/api/Test");
            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(test, _settings.Value);
                    var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);
                    var content_ = new System.Net.Http.FormUrlEncodedContent(dictionary_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                 request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

the test object is an inputdata class not a dictionary so  dictionary_  is always null

>var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(test, _settings.Value);
  var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);

**Pull request merged**
